[project]
name = "basic-keystore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "eth-account>=0.13.0",
    "ruff>=0.15.0",
]
